### PR TITLE
Filled in community assessment for FH Dortmund

### PR DESCRIPTION
**Pull request by spejss**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@spejss not sure if you would like to use **Lists** feature in markdown, the current new line character between two sentences will be removed once your file been parsed as markdown, so the typesetting result may not be the same as you expect. (https://github.com/spejss/fall-2016/blob/master/communities/dortmund-student-hackers/community-assessment.md)

I also found that you send this pull request from your forked master branch, IMO I'll respectfully suggest you create a new branch for this PR and all other PRs in future, so that you can keep your master branch clean, and synced with upstream, using master branch to send pull request may make you a little bit harder to send the other PRs (especially at the same time) and keep your master branch synced with upstream :)

**Comment by kim-codes** [comment]
Under Size, try to add a goal here. Something like gain one new member by the end of the year or double the current number of members. 

Under Resources, try to expand on what resources you would like to add to the community. I also organize a hackathon once a year! Super rewarding. I hope to check yours out maybe ;) 

Under Accessibility, since resources are hard to get a possibility would be to choose just **one** area you would like to improve and how you would go about improving that area or obtaining the resource. 

Under Goals, I love the idea of lightning talks! Now that you know what you would like to do set a goal of when you would like to host your first set. Consider things like how often you would like to host them, every 2-3 weeks? Take into consideration midterms and finals. You mention students want to connect with companies, but companies have trouble reaching out. Try to think of ways you can bridge that gap, a possible networking night like a wine & cheese, etc.

**Comment by spejss** [comment]
Thank you :) 
@kim-codes what hackathon do you organize?

I think that letting companies to reach out to students by speaking/being present at these meetups would be a better idea, than organizing another career fair (there is already atleast one a month). 

Finals are not at the same time in both schools, but it is something that I'd have to take into consideration (atleast the exams of CS departments from both schools).

**Comment by kim-codes** [comment]
@spejss I organize ConUHacks in January in Canada :) ! 

I like your point about a less formal meeting between companies and students. Providing a setting where students can interact with companies without the pressure of finding a job. Good stuff ! :D Great assessment.

**Pull request merged**
