### PR TITLE
Community Assessment for Queensland University of Technology

### PR DESCRIPTION
**Pull request by trjstewart**

### CODE REVIEW

**Comment by Lionex** [comment]
You seem to have modified the community assessment inside of `docs/` instead of creating your own inside of `communities/community-name/`.

**Comment by trjstewart** [comment]
Yep, that one I completely missed. Will have to fix that up.

**Comment by joenash** [comment]
Hey @trjstewart!

You've opened this PR as changes to the community-assessment.md under docs! So we can merge everyone's changes, can you create the new file as described here:

> Save your community assessment document in a folder titled communities, and then create an additional subfolder with the name of your community. For example, if I was creating a community assessment for Women of Color in Savannah, I'd create: communities/woc-savannah/community-assessment.md. If I was creating a community for London Hackers, the path would be: communities/london-hackers/community-assessment.md.

Apologies, this was contained in the week 1 todo and I think quite a few people missed it!

**Comment by trjstewart** [comment]
That should do the trick @joenash.

**Pull request merged**
